export default [
  {
    name: "Nuxt + Sanity Performance and Core Web Vitals Overhaul",
    type: "Corporate",
    description:
      "Three-month performance sprint (Oct-Dec 2025) on an FDA-regulated pharma marketing site built with Nuxt 4, Sanity, and Vercel. Closed 18+ optimization PRs against a September baseline audit. Removed unused WebGL/GLSL bundling, moved GSAP and Google Maps off the global bundle, and converted decorative assets to WebP. Replaced an ad-hoc 39-line lazy-loader with NuxtImg/Sanity provider integration site-wide across ~20 components in a single 66-file PR, restoring responsive sizes, WebP auto-format, and below-fold lazy loading. Split homepage and slug-page GROQ queries into above-the-fold critical and below-the-fold lazy buckets across 9 commits, shrinking the blocking payload that gated LCP on every CMS-driven page. Restructured the full Aeonik Pro font family into a subsetted woff+woff2 layout, added Anaheim with Latin, Latin-Ext, and Vietnamese subsets, and preloaded above-the-fold weights from the Sanity CDN. Configured Vercel edge caching for videos, PDFs, images, fonts, and captions with 7 to 30 day TTLs. Diagnosed and shipped a 4-commit Core Web Vitals fix (prerender/ISR conflict, browser cache headers, animation threshold, asset caching) that moved all 10 indexed URLs in Google Search Console from 'Needs improvement' to 'Good' within 48 hours.",
    skills: [
      "Nuxt.js",
      "Vue",
      "Sanity",
      "GROQ",
      "TypeScript",
      "Vercel",
      "ISR",
      "Core Web Vitals",
      "Web Performance",
      "WebGL",
      "GSAP",
      "WebP",
      "Lazy Loading",
      "Font Subsetting",
      "Edge Caching",
      "CDN",
      "Google Search Console",
    ],
  },
  {
    name: "Sanity-to-Vercel ISR Revalidation Webhook",
    type: "Corporate",
    description:
      "Built an HMAC-verified Sanity webhook to Vercel ISR revalidation route on a Nuxt 4 marketing site. Replaced time-based revalidation with on-demand invalidation, cutting content publish-to-live propagation from up to 60 minutes down to 2-3 minutes and saving an estimated $40/month in ISR write costs. Included signature verification and selective path invalidation driven by the Sanity document type and slug.",
    skills: [
      "Sanity",
      "Vercel",
      "ISR",
      "Webhooks",
      "HMAC",
      "Nuxt.js",
      "TypeScript",
      "Node.js",
    ],
  },
  {
    name: "Production Support for an FDA-Regulated Pharma Marketing Site",
    type: "Corporate",
    description:
      "Ongoing 24/7 two-shift coverage rotation on a Nuxt 4 + Sanity + Vercel pharma marketing site under FDA-regulated content constraints. Sustained 100% production uptime since November 2025 and a Sentry performance score of 93 (7-day rolling) by January 2026. Diagnosed a 5-day silent GA4 tracking blackout (CSP blocking regional endpoints, missing nonce on inline gtag init), rebuilt CSP with wildcards, wired violations to Sentry, and added a Playwright check asserting window.gtag on every merge. Audited 1.66 TB of monthly Vercel egress and identified hardcoded MP4 patient videos as the dominant cost driver.",
    skills: [
      "Nuxt.js",
      "Sanity",
      "Vercel",
      "Sentry",
      "Playwright",
      "Content Security Policy",
      "Google Analytics 4",
      "Production Support",
      "Incident Response",
      "On-Call",
    ],
  },
  {
    name: "Rico Rico",
    type: "Personal",
    url: "https://ricorico.vercel.app/",
    repositoryUrl:
      "https://github.com/luismartinezs/restaurant-reservation-system",
    description:
      "Rico Rico is a demo frontend for a restaurant-reservation booking platform that connects diners with its partner restaurants. The site is built with React/Next.js with Typescript, Mantine and TailwindCSS, and uses Supabase for database and authentication. Images for restaurants are generated using Stable Diffusion models. Integration with the Storyblok CMS allows editors to create custom landing pages for restaurants",
    skills: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Mantine",
      "Storyblok CMS",
      "Supabase",
      "AI image generation",
      "Vercel",
    ],
  },
  {
    name: "Telegram AI Bot Project Bulldozer",
    type: "Personal",
    url: "https://t.me/ProjectBullzoderBot",
    description:
      "The Bulldozer Telegram bot is a multi-functional chatbot integrated with Telegram, OpenAI, Stripe, and Cloudflare. It handles user conversations, subscriptions, and invoicing. It supports conversation aware chat and images. It is deployed via Cloudflare Workers and connects to a SQLite database",
    skills: [
      "Telegram Bot Development",
      "TypeScript",
      "Stripe Integration",
      "OpenAI Integration",
      "Serverless Architecture",
      "SQLite",
      "Webhooks",
      "Cloudflare Workers",
      "JavaScript",
      "API Development",
      "Cloudflare D1 Database",
      "Ngrok",
      "Zod",
      "DevOps",
    ],
  },
  {
    name: "React Katas AI Maker",
    type: "Personal",
    url: "https://react-katas-ai-maker.vercel.app/",
    repositoryUrl: "https://github.com/luismartinezs/react-katas-ai-workflow",
    description:
      "React Katas AI Maker is an app that takes React docs as input, gives the user a few options and outputs the full code for an AI generated React Kata, including final code, starting code and README file, to practice the concepts.",
    skills: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "Vercel",
      "shadcn/ui",
      "OpenAI API",
    ],
  },
  {
    name: "Checklist App for Elden Ring",
    type: "Personal",
    url: "https://eldenringbuilds.vercel.app",
    repositoryUrl: "https://github.com/luismartinezs/react-katas-ai-workflow",
    description:
      "A personal project built from scratch with Next.js, React and Tailwind CSS, with currently around 100 daily users. It shows a checklist of items for the videogame Elden Ring. The user can create a profile and persist the checked items. The app is fully client side so the data is stored in the browser.",
    skills: ["React", "Next.js", "Tailwind CSS", "TypeScript", "Vercel", "PWA"],
  },
  {
    name: "Improving Accessibility and Styles of a PHP Website",
    type: "Corporate",
    description:
      "This is a website to view and publish data samples related to scientific publications. As the front-end and accessibility developer, I performed accessibility audits, created GitHub issues, and fixed existing issues. I also updated the admin pages from legacy to modern styles and updated the style guide to include these updates. Finally, I revamped and improved the accessibility of a Vue widget used to upload large files.",
    skills: [
      "HTML",
      "CSS",
      "Javascript",
      "Accessibility",
      "PHP",
      "jQuery",
      "Bootstrap",
    ],
  },
  {
    name: "Travel Booking Websites Improvement",
    type: "Corporate",
    description:
      "Onboarded as a front-end developer, I championed major improvements in the Nuxt.js a codebase for travel website allowing package bookings.\n\nI targeted large, complex components and initiated a shift towards smaller, single-responsibility modules, vastly enhancing code clarity and maintenance. I corrected Vuex store misuses, transitioned actions to getters, and refactored while shipping features delivery timelines. I delivered features such as advanced web search filters and dynamic campaign pages, boosting user experience. I also filled gaps in end-to-end testing, solidifying the codebase against potential bugs.\n\nThe engagement culminated in a handover to a new developer, leaving behind a substantially improved and streamlined codebase.",
    skills: ["Vue", "Nuxt.js", "Vuex"],
  },
  {
    name: "Improving Accessibility in a React App",
    type: "Corporate",
    description:
      "This project involved improving the accessibility of a React app for a client. After an initial accessibility audit, we identified several tickets that needed to be fixed. I worked on these tickets in a separate branch and made sure to submit pull requests that were easy to understand and review. Once the important tickets were completed, I conducted a full accessibility audit of the app to identify additional issues. I grouped these issues into new tickets and prioritized them based on their importance. Then I worked on the most important tickets to fix them. As a result, the app became fully accessible, and a second accessibility audit resulted in essentially zero issues reported. My contributions to this project helped ensure that the app was usable and accessible to a broader audience.",
    skills: [
      "React",
      "TypeScript",
      "JavaScript",
      "Accessibility",
      "WCAG 2",
      "HTML5",
      "CSS",
      "Sass",
      "RxJS",
    ],
  },
  {
    name: "Habits App",
    type: "Personal",
    url: "https://rotations-6f39b.firebaseapp.com/",
    description:
      "A web app built with React, Firebase, TailwindCSS, and Mantine.dev and bootstrapped from my React starter template. The server state was handled with React-Query, and the global client state was conducted with Redux Toolkit. It allows the user to schedule habits. For example, the user may create a routine titled 'water the plants' with a recurrence of one day.",
    skills: [
      "React",
      "TypeScript",
      "Firebase",
      "Mantine",
      "Redux Toolkit",
      "Tailwind CSS",
      "Vite",
      "ESLint",
      "plop",
    ],
  },
  {
    name: "Weather Wardrobe Wizard",
    type: "Personal",
    url: "https://weather-wardrobe-wizard.netlify.app/",
    repositoryUrl: "https://github.com/luismartinezs/weather-wardrobe-wizard",
    description:
      "The Weather Wardrobe Wizard sends users weather forecasts and corresponding clothing suggestions. Users can toggle between metric and imperial units, list and image view of clothing, and light and dark themes. Selections are locally stored for guest users, while signed-in users have persistent data stored in Firebase. Premium users enjoy AI-powered packing recommendations from OpenAI. The application was developed with Next.js, React, TypeScript, and Zustand and combines weather forecasts with clothing advice. OpenWeather API powers the real-time data, and the UI is crafted with Chakra UI. Firebase Firestore handles real-time database updates, while Stripe facilitates payments for premium services. Multi-language support and error tracking with Sentry are other key features.",
    skills: [
      "React",
      "TypeScript",
      "Next.js",
      "OpenAI API",
      "Chakra UI",
      "Zustand",
      "React Query",
      "Immer",
      "React Hook Form",
      "Firebase",
      "internationalization",
      "Recharts",
      "Stripe",
      "Sentry",
      "Jest",
      "Testing Library",
      "Playwright",
    ],
  },
  {
    name: "Trello Scope Tracker",
    type: "Personal",
    repositoryUrl: "https://github.com/luismartinezs/trello-scope-tracker",
    description:
      "A cloud function deployed on AWS with the serverless framework intercepting webhooks from Trello. When a Trello card is moved to a specific list in the Trello board, the cloud function receives a webhook that triggers a zap from Zapier. This zap appends a value to a Google Sheets spreadsheet.",
    skills: ["Serverless", "Javascript", "Node.js", "Google Sheets"],
  },
  {
    name: "My Personal Website",
    type: "Personal",
    url: "https://www.webdevluis.com/",
    repositoryUrl: "https://github.com/luismartinezs/luis-martinez-next-site",
    description:
      "A website built in Next.js in static site generation mode, enabling loading times to speed up. The site is styled using Tailwind CSS and Storyblok CMS as a content editor, and it is deployed to Netlify.",
    skills: ["React", "Next.js", "Tailwind CSS", "Storyblok CMS", "Netlify"],
  },
  {
    name: "Vue Admin Dashboard Maintenance",
    type: "Corporate",
    description:
      "Contribution to the migration of an admin dashboard from Backbone to Vue 2. Maintained the project for two years. The admin dashboard was a complex web app whose main two features were managing the landing page content where users could apply and managing the applicants themselves through multiple application stages.",
    skills: ["Vue", "Vuex", "Vue Router", "HTML", "CSS", "JavaScript"],
  },
  {
    name: "Content Editor Dashboard",
    type: "Corporate",
    description:
      'Contributed to creating a content editor dashboard powered by Vue 3 and Vite. The dashboard was used to create and edit new entries in the database and set them as "published." My main contribution was to develop the form to interact with those entries.',
    skills: ["Vue", "Vite", "Tailwind CSS", "JavaScript", "HTML", "CSS"],
  },
  {
    name: "Landing Page Editor",
    type: "Corporate",
    description:
      "A Nuxt component library built for Jobsrepublic was integrated with the Storyblok CMS so that content managers could create and edit new landing pages from scratch. Every component included team brainstorming with the content creators to cater to their needs, a development phase and accessibility, and performance and SEO audit to achieve a high lighthouse rank. Changes requested by the team were implemented often within the same day. Tailwind CSS was used for styling, and the UI design was adapted from that provided by the Tailwind UI template library. Each landing page was its own multipage site.",
    skills: [
      "Nuxt.js",
      "Vue",
      "Tailwind CSS",
      "Storyblok CMS",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    name: "Multi-site Codebase Maintenance",
    type: "Corporate",
    description:
      "Maintained a multi-site codebase built with Nuxt.js. One of these sites was a big portal with a large traffic of up to 100,000 monthly visitors. Evolved the codebase, adding new pages, implementing design changes, improving accessibility, performance, and creating a more SEO-friendly URL structure with crawlable pagination and performance.",
    skills: [
      "Nuxt.js",
      "Vue",
      "Bootstrap",
      "Storyblok CMS",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    name: "Conversion Tracker App",
    type: "Corporate",
    description:
      "A single-page application built for Jobsrepublic, with data visualization related to social media campaigns and landing pages, namely, KPIs of conversion funnels, plots of a magnitude versus time, and tabular data. The app was built from scratch to production-ready with Vue 2, Auth0 for authentication, multi-language, and E2E tests with the TestCafe testing library. The data was consumed from a REST API built by the back-end team. The layout used a customized Vue Bootstrap theme. At the start of the project, coding best practices were established and documented.",
    skills: [
      "Vue",
      "Bootstrap",
      "Auth0",
      "JavaScript",
      "HTML",
      "CSS",
      "i18n",
      "TestCafe",
      "E2E Testing",
    ],
  },
  {
    name: "AthleanX Home Workout App",
    type: "Personal",
    url: "https://ahtleanx-home-workout.netlify.app/",
    repositoryUrl: "https://github.com/luismartinezs/ahtleanx-home-workout-app",
    description:
      "A progressive web application for mobile devices that helps with workouts at home. The app is a static single-page application developed with Vue 2 that behaves like a native mobile app. I designed and created the UI from scratch using Figma and Tailwind CSS.",
    skills: [
      "Vue 2",
      "Tailwind CSS",
      "Figma",
      "Vuex",
      "Vue router",
      "ESLint",
      "PWA",
      "UI Design",
      "Mobile Web Development",
      "Frontend Development",
      "ECMAScript (ES6)",
    ],
  },
];
