export default [
  { "star": true, "name": "CSS", "years": 5 },
  { "star": true, "name": "JavaScript", "years": 5 },
  { "star": true, "name": "HTML5", "years": 5 },
  { "star": true, "name": "Vue", "years": 3 },
  { "star": true, "name": "React", "years": 2 },
  { "name": "Storyblok", "years": 2 },
  { "star": true, "name": "Tailwind CSS", "years": 4 },
  { "name": "Firebase", "years": 1 },
  { "name": "Adobe Photoshop", "years": 5 },
  { "name": "APIs", "years": 5 },
  { "name": "ECMAScript (ES6)", "years": 5 },
  { "star": true, "name": "Front-end Development", "years": 5 },
  { "star": true, "name": "Web Development", "years": 5 },
  { "name": "JavaScript Libraries", "years": 5 },
  { "name": "Responsive Layout", "years": 5 },
  { "name": "Responsive Web Design (RWD)", "years": 5 },
  { "name": "Testing", "years": 5 },
  { "name": "User Interface (UI)", "years": 5 },
  { "name": "Agile Software Development", "years": 3 },
  { "name": "API Integration", "years": 3 },
  { "name": "Babel", "years": 3 },
  { "name": "Bash", "years": 3 },
  { "name": "CSS3", "years": 5 },
  { "name": "ESLint", "years": 5 },
  { "name": "Flexbox", "years": 5 },
  { "name": "Front-end", "years": 5 },
  { "name": "Git", "years": 5 },
  { "name": "GitHub", "years": 5 },
  { "name": "GitLab", "years": 3 },
  { "name": "HTML", "years": 5 },
  { "name": "HTML DOM", "years": 5 },
  { "name": "Jira", "years": 3 },
  { "name": "JSON", "years": 5 },
  { "name": "Linux", "years": 5 },
  { "name": "Lodash", "years": 3 },
  { "name": "NPM", "years": 5 },
  { "name": "Remote Work", "years": 4 },
  { "name": "REST APIs", "years": 3 },
  { "name": "Scrum", "years": 3 },
  { "name": "Slack", "years": 5 },
  { "name": "Spreadsheets", "years": 3 },
  { "name": "Ubuntu", "years": 5 },
  { "name": "Ubuntu Linux", "years": 5 },
  { "name": "UI Components", "years": 5 },
  { "name": "UI Frameworks", "years": 5 },
  { "name": "Visual Studio Code (VS Code)", "years": 5 },
  { "name": "Vue 2", "years": 3 },
  { "name": "Vuex", "years": 3 },
  { "name": "Web UX", "years": 3 },
  { "name": "Webpack 4", "years": 3 },
  { "name": "Wireframe to Product", "years": 3 },
  { "name": "Wireframing", "years": 3 },
  { "name": "Amazon Elastic Container Service (Amazon ECS)", "years": 2 },
  { "name": "Amazon Route 53", "years": 2 },
  { "name": "Amazon S3 (AWS S3)", "years": 2 },
  { "name": "Auth0", "years": 2 },
  { "name": "Bootstrap", "years": 4 },
  { "name": "Bootstrap 4", "years": 3 },
  { "name": "Bootstrap 3", "years": 1 },
  { "name": "Component Libraries", "years": 2 },
  { "name": "Content Management Systems (CMS)", "years": 2 },
  { "name": "Jest", "years": 2 },
  { "star": true, "name": "Nuxt.js", "years": 2 },
  { "name": "PostgreSQL", "years": 2 },
  { "name": "SCSS", "years": 3 },
  { "name": "Startups", "years": 2 },
  { "name": "TestCafe", "years": 2 },
  { "name": "UI Libraries", "years": 2 },
  { "name": "UI Testing", "years": 2 },
  { "name": "Zapier", "years": 2 },
  { "name": "A11Y", "years": 2 },
  { "name": "Accessibility", "years": 2 },
  { "name": "Adobe After Effects", "years": 1 },
  { "name": "Adobe Illustrator", "years": 1 },
  { "name": "Amazon Web Services (AWS)", "years": 1 },
  { "name": "AWS Certificate Manager", "years": 1 },
  { "name": "AWS Lambda", "years": 1 },
  { "name": "Blender", "years": 1 },
  { "name": "CI/CD Pipelines", "years": 1 },
  { "name": "Cloud Firestore", "years": 1 },
  { "name": "Cloudflare", "years": 1 },
  { "name": "Cloudflare Workers", "years": 1 },
  { "name": "CSS Grid", "years": 1 },
  { "name": "Data Visualization", "years": 1 },
  { "name": "Docker", "years": 1 },
  { "name": "Elastic Load Balancers", "years": 1 },
  { "name": "Express.js", "years": 1 },
  { "name": "Figma", "years": 1 },
  { "name": "Firebase Authentication", "years": 1 },
  { "name": "Firebase Hosting", "years": 1 },
  { "name": "Full-stack", "years": 1 },
  { "name": "GitLab CI/CD", "years": 1 },
  { "name": "Google Apps Script", "years": 1 },
  { "name": "JSX", "years": 2 },
  { "name": "Mantine", "years": 1 },
  { "name": "Netlify", "years": 2 },
  { "star": true, "name": "Next.js", "years": 2 },
  { "name": "Node.js", "years": 1 },
  { "name": "OAuth 2", "years": 1 },
  { "name": "Performance", "years": 1 },
  { "name": "React Components", "years": 2 },
  { "name": "React Hooks", "years": 2 },
  { "name": "React Query", "years": 1 },
  { "name": "React Redux", "years": 1 },
  { "name": "React Testing Library", "years": 1 },
  { "name": "Redis", "years": 1 },
  { "name": "Redux", "years": 1 },
  { "name": "RxJS", "years": 1 },
  { "name": "Sanity Studio", "years": 1 },
  { "name": "Sass", "years": 1 },
  { "name": "Search Engine Optimization (SEO)", "years": 1 },
  { "name": "Sentry", "years": 1 },
  { "name": "Serverless", "years": 1 },
  { "name": "Serverless Framework", "years": 1 },
  { "name": "SSH", "years": 1 },
  { "name": "Storybook", "years": 1 },
  { "star": true, "name": "TypeScript", "years": 2 },
  { "name": "TypeScript 2", "years": 2 },
  { "name": "TypeScript 3", "years": 2 },
  { "name": "UI Design", "years": 1 },
  { "name": "UX Design", "years": 1 },
  { "name": "Vite", "years": 1 },
  { "name": "Vitest", "years": 1 },
  { "name": "Vue 3", "years": 1 },
  { "name": "WCAG 2", "years": 2 },
  { "name": "Yarn", "years": 1 },
  { "name": "Booking Systems" },
  { "name": "Chakra UI", "years": 1 },
  { "name": "Firebase Cloud Functions" },
  { "name": "i18n" },
  { "name": "Less" },
  { "name": "Multilingual Websites" },
  { "name": "OpenAI API", "years": 2 },
  { "name": "PHP" },
  { "name": "Playwright" },
  { "name": "Progressive Web Applications (PWA)", "years": 2 },
  { "name": "Recharts" },
  { "name": "Selenium" },
  { "name": "Stripe API", "years": 1 },
  { "name": "User Experience (UX)" },
  { "name": "Vercel", "years": 2 },
  { "star": true, "name": "Web Accessibility", "years": 2 },
  { "name": "Zustand", "years": 1 }
]